
volumes:
  db-backups:

services:
  dbbackups:
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        POSTGRES_MAJOR_VERSION: "${POSTGRES_MAJOR_VERSION}"
    image: dbbackups_image:${POSTGRES_MAJOR_VERSION}
    volumes:
      - db-backups:/backups
    environment:
      - DUMPPREFIX=PG
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - RUN_AS_ROOT=true
      - CRON_SCHEDULE="*/5 * * * *"
      - CONSOLE_LOGGING=TRUE
      #- DB_DUMP_ENCRYPTION=true
      #- DB_TABLES=TRUE
    restart: on-failure
